services:
  class-management:
    image: class-management
    build:
      context: .
      dockerfile: ClassManagementWebApi/Dockerfile
  db:
    image: postgres:latest
    container_name: postgres_container-class-management
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: classManagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: